### ISSUE TITLE
Confirm overwrite existing file?

### ISSUE THREAD

**Issue by mitchtbaum** [quadrupleslap/srs#1]

**Comment by mitchtbaum** [comment]
It's missing a slash.

Here's an Arch Linux yaourt install prompt, for example:
![y-n](https://user-images.githubusercontent.com/584077/43040894-b1331516-8d05-11e8-92ef-aa907a527ea8.png)

**Comment by quadrupleslap** [comment]
Thanks! Closed by ee32d68.
